# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "MLE"
  url = "#"
  weight = 10


[[main]]
  name = "News"
  url = "news/"
  weight = 20


[[main]]
  name = "Team"
  url = "team/"
  identifier = "team"
  weight = 30

[[main]]
  name = "MLE-Koordination"
  url = "team/#leitung"
  parent = "team"
  weight = 1

[[main]]
  name = "Team TUHH"
  url = "team/#tuhh"
  parent = "team"
  weight = 2

[[main]]
  name = "Team Hereon"
  url = "team/#hereon"
  parent = "team"
  weight = 3

[[main]]
  name = "Affiliates"
  url = "team/#affiliates"
  parent = "team"
  weight = 4


[[main]]
  name = "Aktivitäten"
  url = "activities/"
  identifier = "activities"
  weight = 40

[[main]]
  name = "MLE-Days"
  url = "activities/#mle_days"
  parent = "activities"
  weight = 1

[[main]]
  name = "MLE-School"
  url = "activities/#mle_school"
  parent = "activities"
  weight = 2

[[main]]
  name = "Train Your Engineering Network"
  url = "activities/#network"
  parent = "activities"
  weight = 3

[[main]]
  name = "Archiv"
  url = "_archive/activities"
  parent = "activities"
  weight = 4


[[main]]
  name = "Forschung"
  url = "research/"
  identifier = "research"
  weight = 50

[[main]]
  name = "Themen"
  url = "research/#projects"
  parent = "research"
  weight = 1

[[main]]
  name = "Publikationen"
  url = "research/#publications"
  parent = "research"
  weight = 2

[[main]]
  name = "Kompetenzen"
  url = "research/#competences"
  parent = "research"
  weight = 3

[[main]]
  name = "Methoden"
  url = "_repos/methods/"
  parent = "research"
  weight = 4


[[main]]
  name = "Arbeitsgruppen"
  url = "workinggroups/"
  identifier = "workinggroups"
  weight = 60

[[main]]
  name = "HULKs@TUHH - RoboCup SPL Team"
  url = "workinggroups/#hulks"
  parent = "workinggroups"
  weight = 1

[[main]]
  name = "AG Physics-based Machine Learning"
  url = "workinggroups/#pb_ml"
  parent = "workinggroups"
  weight = 2


[[main]]
  name = "Transfer"
  url = "transfer/"
  identifier = "transfer"
  weight = 70

[[main]]
  name = "Angebote"
  url = "transfer/#pillars"
  parent = "transfer"
  weight = 1

[[main]]
  name = "Komponenten"
  url = "transfer/#offerings"
  parent = "transfer"
  weight = 2

  [[main]]
  name = "Partnerschaft"
  url = "transfer/#cooperation"
  parent = "transfer"
  weight = 3


[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 80
