# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "MLE"
  url = "#"
  weight = 10

[[main]]
  name = "Team"
  url = "team/"
  weight = 20






[[main]]
  name = "Forschung"
  url = "research/"
  identifier = "research"
  weight = 30

[[main]]
  name = "Themen"
  url = "research/"
  parent = "research"
  weight = 1

[[main]]
  name = "Publikationen"
  url = "research/#publications"
  parent = "research"
  weight = 2

[[main]]
  name = "ML-Methoden"
  url = "_repos/methods/"
  parent = "research"
  weight = 3




[[main]]
  name = "Events"
  url = "events/"
  identifier = "events"
  weight = 40

[[main]]
  name = "ML with Matlab"
  url = "events/#matlab"
  parent = "events"
  weight = 1

[[main]]
  name = "ML Engineering Network"
  url = "events/#network"
  parent = "events"
  weight = 2

[[main]]
  name = "In Planung"
  url = "events/#planung"
  parent = "events"
  weight = 3




# [[main]]
#   name = "MLE-Days"
#   url = "conference/"
#   weight = 50





[[main]]
  name = "Transfer"
  url = "transfer/"
  identifier = "transfer"
  weight = 60
  
[[main]]
  name = "Angebote"
  url = "transfer/"
  parent = "transfer"
  weight = 1

[[main]]
  name = "Engineering"
  url = "engineering/"
  parent = "transfer"
  weight = 2

[[main]]
  name = "Business"
  url = "business/"
  parent = "transfer"
  weight = 3

[[main]]
  name = "Training"
  url = "training/"
  parent = "transfer"
  weight = 4





[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 70




