# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "MLE"
  url = "#"
  weight = 10

  [[main]]
  name = "News"
  url = "news/"
  weight = 20

[[main]]
  name = "Team"
  url = "team/"
  identifier = "team"
  weight = 30


[[main]]
  name = "MLE-Koordination"
  url = "team/#leitung"
  parent = "team"
  weight = 1

[[main]]
  name = "Team TUHH"
  url = "team/#tuhh"
  parent = "team"
  weight = 2

[[main]]
  name = "Team Hereon"
  url = "team/#hereon"
  parent = "team"
  weight = 3

[[main]]
  name = "Affiliates"
  url = "team/#affiliates"
  parent = "team"
  weight = 4



[[main]]
  name = "Forschung"
  url = "research/"
  identifier = "research"
  weight = 40

[[main]]
  name = "Themen"
  url = "research/"
  parent = "research"
  weight = 1

[[main]]
  name = "Publikationen"
  url = "research/#publications"
  parent = "research"
  weight = 2

[[main]]
  name = "ML-Methoden"
  url = "_repos/methods/"
  parent = "research"
  weight = 3

[[main]]
  name = "ML-Kompetenzen"
  url = "https://competences.mle.hamburg"
  parent = "research"
  weight = 4


[[main]]
  name = "Lehre"
  url = "lehre/"
  identifier = "lehre"
  weight = 50

[[main]]
  name = "Train Your Engineering Network"
  url = "lehre/#network"
  parent = "lehre"
  weight = 1

[[main]]
  name = "Archiv"
  url = "_archive/lehre"
  parent = "lehre"
  weight = 3


[[main]]
  name = "Arbeitsgruppen"
  url = "workinggroups/"
  identifier = "workinggroups"
  weight = 55

[[main]]
  name = "HULKs@TUHH - RoboCup SPL Team"
  url = "workinggroups/#hulks"
  parent = "workinggroups"
  weight = 1

[[main]]
  name = "AG Physics-based Machine Learning"
  url = "workinggroups/#hybrid_pb_ml"
  parent = "workinggroups"
  weight = 2


[[main]]
  name = "Transfer"
  url = "transfer/"
  identifier = "transfer"
  weight = 60

[[main]]
  name = "MLE-Days"
  url = "https://www.mle-days.hamburg"
  parent = "transfer"
  weight = 1
  
[[main]]
  name = "Angebote"
  url = "transfer/"
  parent = "transfer"
  weight = 2

[[main]]
  name = "Network & Exchange"
  url = "network_and_exchange/"
  parent = "transfer"
  weight = 3

[[main]]
  name = "Training & Executive Education"
  url = "training_and_executive_education/"
  parent = "transfer"
  weight = 4

[[main]]
  name = "Consulting & Transformation"
  url = "consulting_and_tranformation/"
  parent = "transfer"
  weight = 5

[[main]]
  name = "Customized Project Development"
  url = "customized_project_development/"
  parent = "transfer"
  weight = 6





[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 70




